templateDir: python/templates
packageName: 'stencila.hub'
packageUrl: https://pypi.org/project/stencila.hub/
packageVersion: 4.27.12
infoName: Stencila and contributors
infoEmail: hello@stenci.la
licenseInfo: Apache 2.0
